# Conexión a Supabase usando Session Pooler (IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.jpudtlgjxlihmmqwvbtd
spring.datasource.password=Donalo3004*

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
project.build.sourceEncoding=UTF-8